apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{- include "albbasic.labels" . | nindent 4 }}
  name: {{ include "albbasic.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}    # External port
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}  # Port on pod
    nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "albbasic.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}