{{- if .Values.template.create -}}
apiVersion: v1
kind: {{.Values.template.name}}
metadata:
  name: {{.Values.template.name}}
  {{- with .Values.custom.labels }}
  labels:
  {{- toYaml . | nindent 4}}
  {{- end}}
{{- end }}
